# Generated by Django 4.2.6 on 2023-10-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='Nilai Default', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='detail',
            field=models.CharField(default='Nilai Default', max_length=255),
        ),
    ]
