# Generated by Django 4.2.6 on 2023-10-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_description_blog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(default='', upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
